In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("ecommerce_dataset.csv")

In [3]:
df.head()

,Order_ID,Customer_Name,Email,Product_ID,Product_Category,Quantity,Unit_Price,Shipping_Cost,Payment_Method,Delivery_Status,Order_Date
0,ORD-1825,Amit$,NaN,P-100@,Home & Kitchen,5,218.54,NaN,Cash on Delivery,Pending,01/14/2023
1,ORD-1447,Rahul@,test@yahoo.com,P-100@,Electronics,2,477.82,NaN,Credit Card,NaN,30-07-2023
2,ORD-1778,NaN,test@yahoo.com,P-100@,Electronics,one,379.4,NaN,Credit Card,Delivered,06-12-2023
3,ORD-1425,Rahul@,test@yahoo.com,P#200,Electronics,10,319.4,NaN,Paypal,Pending,03/16/2023
4,ORD-2047,Neha!!,wrong@email@.com,P-100@,Electronics,1,120.21,NaN,Net banking,Cancelled,09/20/2023

In [4]:
df.shape

(1200, 11)

In [5]:
# structured way of writing codes
def summary(data):
    print("-"*100)
    print("These are first 10 rows")
    print(df.head(10))
    print()
    print("-"*100)
    print(df.shape)
    print()
    print("-"*100)
    print(df.info())
    print()
    print("-"*100)
    print(df.describe())
summary(df)

----------------------------------------------------------------------------------------------------
These are first 10 rows
   Order_ID Customer_Name             Email Product_ID Product_Category  \
0  ORD-1825         Amit$               NaN     P-100@   Home & Kitchen
1  ORD-1447        Rahul@    test@yahoo.com     P-100@      Electronics
2  ORD-1778           NaN    test@yahoo.com     P-100@      Electronics
3  ORD-1425        Rahul@    test@yahoo.com      P#200      Electronics
4  ORD-2047        Neha!!  wrong@email@.com     P-100@      Electronics
5  ORD-1522           NaN  wrong@email@.com        NaN          Fashion
6  ORD-1244        Ankit#    test@yahoo.com      P_300          Fashion
7  ORD-1749           NaN               NaN      P_300          Fashion
8  ORD-1727        Neha!!               NaN     P-100@      Electronics
9  ORD-1966         Rohit  wrong@email@.com     P-100@              NaN

  Quantity Unit_Price  Shipping_Cost    Payment_Method Delivery_Status  \
0        5     218.54            NaN  Cash on Delivery         Pending
1        2     477.82            NaN       Credit Card             NaN
2      one      379.4            NaN       Credit Card       Delivered
3       10      319.4            NaN            Paypal         Pending
4        1     120.21            NaN       Net banking       Cancelled
5        2     12#0.2            NaN       Credit Card             NaN
6        2      76.14            NaN               NaN       Cancelled
7        2     439.78            NaN       Credit Card         Pending
8      two      320.5            NaN       Credit Card       Cancelled
9        2     368.63            NaN               NaN       Delivered

   Order_Date
0  01/14/2023
1  30-07-2023
2  06-12-2023
3  03/16/2023
4  09/20/2023
5  19-09-2023
6  03/26/2023
7  19-08-2023
8  04-04-2023
9  02-07-2023

----------------------------------------------------------------------------------------------------
(1200, 11)

----------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1200 non-null   str
 1   Customer_Name     1052 non-null   str
 2   Email             985 non-null    str
 3   Product_ID        938 non-null    str
 4   Product_Category  898 non-null    str
 5   Quantity          970 non-null    str
 6   Unit_Price        1200 non-null   str
 7   Shipping_Cost     0 non-null      float64
 8   Payment_Method    951 non-null    str
 9   Delivery_Status   916 non-null    str
 10  Order_Date        1200 non-null   str
dtypes: float64(1), str(10)
memory usage: 103.3 KB
None

----------------------------------------------------------------------------------------------------
       Shipping_Cost
count            0.0
mean             NaN
std              NaN
min              NaN
25%              NaN
50%              NaN
75%              NaN
max              NaN

In [6]:
df.shape

(1200, 11)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1200 non-null   str
 1   Customer_Name     1052 non-null   str
 2   Email             985 non-null    str
 3   Product_ID        938 non-null    str
 4   Product_Category  898 non-null    str
 5   Quantity          970 non-null    str
 6   Unit_Price        1200 non-null   str
 7   Shipping_Cost     0 non-null      float64
 8   Payment_Method    951 non-null    str
 9   Delivery_Status   916 non-null    str
 10  Order_Date        1200 non-null   str
dtypes: float64(1), str(10)
memory usage: 103.3 KB

In [8]:
df.dtypes

Order_ID                str
Customer_Name           str
Email                   str
Product_ID              str
Product_Category        str
Quantity                str
Unit_Price              str
Shipping_Cost       float64
Payment_Method          str
Delivery_Status         str
Order_Date              str
dtype: object

In [9]:
df.describe()

       Shipping_Cost
count            0.0
mean             NaN
std              NaN
min              NaN
25%              NaN
50%              NaN
75%              NaN
max              NaN

In [10]:
df.isnull().sum()

Order_ID               0
Customer_Name        148
Email                215
Product_ID           262
Product_Category     302
Quantity             230
Unit_Price             0
Shipping_Cost       1200
Payment_Method       249
Delivery_Status      284
Order_Date             0
dtype: int64

In [11]:
df.Order_ID.value_counts()

Order_ID
ORD-1197    6
ORD-1749    5
ORD-1378    5
ORD-2168    5
ORD-1558    5
           ..
ORD-1755    1
ORD-2110    1
ORD-2147    1
ORD-1450    1
ORD-1313    1
Name: count, Length: 754, dtype: int64

In [12]:
df.sort_values(by = "Unit_Price")

,Order_ID,Customer_Name,Email,Product_ID,Product_Category,Quantity,Unit_Price,Shipping_Cost,Payment_Method,Delivery_Status,Order_Date
454,ORD-1722,NaN,test@yahoo.com,P-100@,Electronics,1,100.04,NaN,Credit Card,Delivered,11/13/2023
676,ORD-2117,Rohit,test@yahoo.com,NaN,Home & Kitchen,2,100.42,NaN,Cash on Delivery,NaN,12/16/2023
809,ORD-1837,S@nja y,demo@outlook.com,P_300,Electronics,NaN,100.96,NaN,Paypal,NaN,10-03-2023
181,ORD-2074,Priya,demo@outlook.com,NaN,NaN,1,101.06,NaN,Credit Card,Cancelled,26-03-2023
546,ORD-2086,NaN,wrong@email@.com,P-100@,NaN,1,101.1,NaN,Credit Card,NaN,15-01-2023
...,...,...,...,...,...,...,...,...,...,...,...
634,ORD-1393,Rahul@,demo@outlook.com,P-100@,NaN,10,98.23,NaN,Paypal,Pending,02-06-2023
99,ORD-1463,NaN,test@yahoo.com,P_300,Fashion,10,98.55,NaN,NaN,Cancelled,08-12-2023
123,ORD-1270,Rahul@,user@gmail.com,NaN,NaN,5,99.52,NaN,Net banking,Pending,01-08-2023
1067,ORD-1947,Ankit#,test@yahoo.com,P-100@,Home & Kitchen,1,99.71,NaN,Credit Card,Delivered,12-03-2023
770,ORD-1174,NaN,test@yahoo.com,P 400,Home & Kitchen,2,99.78,NaN,Cash on Delivery,Pending,11/18/2023

In [13]:
df.isnull().sum()

Order_ID               0
Customer_Name        148
Email                215
Product_ID           262
Product_Category     302
Quantity             230
Unit_Price             0
Shipping_Cost       1200
Payment_Method       249
Delivery_Status      284
Order_Date             0
dtype: int64

In [14]:
for i in df.columns:
    print(i,df[i].sort_values().unique(),"\n",sep="\n")

Order_ID
<StringArray>
[' ORD-1000 ', ' ORD-1020 ', ' ORD-1040 ', ' ORD-1060 ', ' ORD-1080 ',
 ' ORD-1120 ', ' ORD-1160 ', ' ORD-1220 ', ' ORD-1260 ', ' ORD-1280 ',
 ...
   'ORD-2177',   'ORD-2179',   'ORD-2182',   'ORD-2184',   'ORD-2187',
   'ORD-2188',   'ORD-2189',   'ORD-2192',   'ORD-2194',   'ORD-2199']
Length: 754, dtype: str


Customer_Name
<StringArray>
['Amit$', 'Ankit#', 'Neha!!', 'Priya', 'Rahul@', 'Rohit', 'S@nja y', nan]
Length: 8, dtype: str


Email
<StringArray>
['demo@outlook.com', 'test@yahoo.com', 'user@gmail.com', 'wrong@email@.com',
 nan]
Length: 5, dtype: str


Product_ID
<StringArray>
['P 400', 'P#200', 'P-100@', 'P_300', nan]
Length: 5, dtype: str


Product_Category
<StringArray>
['Electronics', 'Fashion', 'Home & Kitchen', nan]
Length: 4, dtype: str


Quantity
<StringArray>
['1', '10', '2', '5', 'one', 'three', 'two', nan]
Length: 8, dtype: str


Unit_Price
<StringArray>
['100.04', '100.42', '100.96', '101.06',  '101.1', '101.68', '102.14',
 '102.23',  '102.6', '102.68',
 ...
  '96.13',  '96.41',  '96.85',  '97.97',  '98.14',  '98.23',  '98.55',
  '99.52',  '99.71',  '99.78']
Length: 1190, dtype: str


Shipping_Cost
[nan]


Payment_Method
<StringArray>
['Cash on Delivery', 'Credit Card', 'Net banking', 'Paypal', nan]
Length: 5, dtype: str


Delivery_Status
<StringArray>
['Cancelled', 'Delivered', 'Pending', nan]
Length: 4, dtype: str


Order_Date
<StringArray>
['01-01-2023', '01-01-2024', '01-02-2023', '01-03-2023', '01-04-2023',
 '01-05-2023', '01-06-2023', '01-07-2023', '01-08-2023', '01-09-2023',
 ...
 '30-09-2023', '30-10-2023', '30-11-2023', '31-01-2023', '31-03-2023',
 '31-05-2023', '31-07-2023', '31-08-2023', '31-10-2023', '31-12-2023']
Length: 487, dtype: str

In [15]:
df[df.duplicated()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, Email, Product_ID, Product_Category, Quantity, Unit_Price, Shipping_Cost, Payment_Method, Delivery_Status, Order_Date]
Index: []

# Data Cleaning
 - correct the data
- Duplicate value
- capitalise
- Noise values and unwanted spaces
- data type correct
-  Null values

In [16]:
df.Quantity.unique()

<StringArray>
['5', '2', 'one', '10', '1', 'two', nan, 'three']
Length: 8, dtype: str

In [17]:
df.Quantity.replace("five",5,inplace=True) #this is older way of writing code
df["Quantity"] = df["Quantity"].replace("five",5) #this is new way of writing code

C:\Users\RADHIKA PAL\AppData\Local\Temp\ipykernel_14624\2089417582.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.Quantity.replace("five",5,inplace=True) #this is older way of writing code

In [18]:
df.drop_duplicates(inplace=True)
#it will drop all the rows which are repeated not by just checking single column.

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
cat = [] we created an empty list to store the names of categorical columns.
for i in df.columns:
    if df[i].dtypes=="O":
        cat.append(i)
    else:
        pass

SyntaxError: invalid syntax (1861099597.py, line 1)

In [ ]:
cat

['Order_ID',
 'Customer_Name',
 'Email',
 'Product_ID',
 'Product_Category',
 'Quantity',
 'Order_Date',
 'Shipping_Cost',
 'Delivery_Status',
 'Payment_Method']

In [ ]:
cat.remove('Quantity')

In [ ]:
cat

['Order_ID',
 'Customer_Name',
 'Email',
 'Product_ID',
 'Product_Category',
 'Order_Date',
 'Shipping_Cost',
 'Delivery_Status',
 'Payment_Method']

In [ ]:
for i in cat:
    df[i] = df[i].str.capitalize()

In [ ]:
new_col = ['Payment_Method','Product_Category']
for i in new_col:
    df[i] = df[i].replace(r'[^a-zA-Z0-9]',regex=True)

In [ ]:
df["Product_ID"] = df["Product_ID"].replace(r'[^a-zA-Z0-9]',regex=True)

In [ ]:
df["Order_ID"] = df["Order_ID"].str.strip().replace(" ","")

In [ ]:
df[["Price","Quantity"]] = df[["Price","Quantity"]].astype("float32")

In [ ]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])

In [ ]:
df.dtypes

In [ ]:
df.Price.skew()

-0.045179598

In [ ]:
df[["Price","Quantity"]] = df[["Price","Quantity"]].fillna(df[["Price","Quantity"]].mean())

In [ ]:
df.isnull().sum()

Order_ID              0
Customer_Name       174
Email               410
Product_ID          121
Product_Category    359
Quantity              0
Price                 0
Order_Date          245
Shipping_Cost       250
Delivery_Status     196
Payment_Method      473
dtype: int64

In [ ]:
cat

In [ ]:
cat.remove('Product_ID')

In [ ]:
for i in cat:
    df[i] = df[i].fillna("Unknown")

In [ ]:
df["Product_ID"] = df["Product_ID"].fillna( df["Product_ID"].mode()[0]) #most repeated value in the column.

In [ ]:
df.isnull().sum()

In [ ]:
# Data Transformation | creating new columns (feature engineering)
df["Revenue"] = df["Price"]*df["Quantity"]

In [ ]:
df["Price"].describe()

In [ ]:
def new_col(data):
    if data<=150:
        return "Low Price of Product"
    elif data>150 and data<=370:
        return "Medium Price  Of Product"
    else:
        return "High Cost Of Product"

In [ ]:
df["Price_Category"] = df["Price"].apply(new_col) #feature engineering

In [ ]:
df["Price_Category"]

In [ ]:
# df["Price_Category"]df["Price_Category"] = df["Price"].apply(
    lambda x: "Low Cost" if x <= 150 else
              "Medium Cost" if x <= 370 else
              "High Cost"
# ) = np.where(
#     df["Price"] <= 150,
#     "Low Price of Product",
#     np.where(
#         df["Price"] <= 370,
#         "Medium Price Of Product",
#         "High Cost Of Product"
#     )
# )

In [ ]:
df["Price_Category"] = df["Price"].apply(
    lambda x: "Low Cost" if x <= 150 else
              "Medium Cost" if x <= 370 else
              "High Cost"
) #x is the value of price column which is being passed to the function and based on the value of x we are categorizing the price into low cost , medium cost and high cost.

In [ ]:
df['Quantity'].unique()

array([1.      , 2.      , 3.355665, 5.      , 3.      , 4.      ],
      dtype=float32)